image:
- Visual Studio 2019
- macOS

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: cq5sCIvjUPBY6V+SOp37WeHbVBJ+h96CBYh0GNzvpvy5GZOAgvpfUbmkdoTiZ8nxg0XUvbE9tHfXaLjzxLBo/yBpuVgP9PP8dLpDq6u0y3uaR6xPXPo1eOdK7j1oZEJB
    
install:
- pip install -r requirements.txt
- pip install pyinstaller pillow

build_script:
- flet pack main.py --name "BMD-Helper" --icon assets/icon.png --product-name "BMD-Helper" --product-version "0.0.1" --copyright "Copyright (c) 2024 Lightbridge-KS."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a BMD-Helper-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: BMD-Helper-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf BMD-Helper-macos.tar.gz -C dist BMD-Helper.app

  artifacts:
  - path: BMD-Helper-macos.tar.gz
